[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
glam = "0.25.0"
nom = "7.1.3"
nom_locate = "4.2.0"
tracing = "0.1.40"
