project-setup day:
    cargo new {{day}}

new day: (project-setup day)
    echo "Cleainng up and setting up project."
    rip ./{{day}}/src/main.rs && mkdir ./{{day}}/src/bin && cp ./template/bin/* ./{{day}}/src/bin
